### ISSUE TITLE
ReturnTo mit aktuellem Deeplink

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-sso#27]
Bsp:

1. Nicht eingeloggt

Klick auf Unterseite: https://www.intern.rrze.fau.de/anleitungen/veranstaltungen/veranstaltungsuebersicht/lange-nacht-der-wissenschaften/

2. Login
=> redirect zur Startseite https://www.intern.rrze.fau.de

Grund: https://www.intern.rrze.fau.de/simplesaml/module.php/core/as_login.php?AuthId=default-sp&ReturnTo=https%3A%2F%2Fwww.intern.rrze.fau.de

Schön wäre: redirect zu https://www.intern.rrze.fau.de/anleitungen/veranstaltungen/veranstaltungsuebersicht/lange-nacht-der-wissenschaften/

**Comment by rvdforst** [comment]
Dieses Problem wurde nun behoben.
